var md5 = require("MD5");

const pageKeys = {
  reception: "reception",
  receptionDrawer: md5("receptionDrawer"),
  receptionDrawerInterior: md5("receptionDrawerInterior"),
  receptionDrawerPostit: md5("receptionDrawerPostit"),
  receptionDrawerMap: md5("receptionDrawerMap"),
  receptionDrawerSecuritySheet: md5("receptionDrawerSecuritySheet"),
  receptionDrawerEmployeeReport: md5("receptionDrawerEmployeeReport"),
  receptionLift: md5("receptionLift"),
  lobby7Floor: md5("lobby7Floor"),
  staffBar: md5("staffBar"),
  ceoOffice: md5("ceoOffice"),
  ceoOfficeInterior: md5("ceoOfficeInterior"),
  ceoSafe: md5("ceoSafe"),
  ceoDestinationSolved: md5("ceoDestinationSolved"),
  staffBarInterior: md5("staffBarInterior"),
  barComputer: md5("barComputer"),
  barSafe: md5("barSafe"),
  barComputerInterior: md5("barComputerInterior"),
  barComputerInteriorPart2: md5("barComputerInteriorPart2"),
  barSafeInterior: md5("barSafeInterior"),
  financeDepartment: md5("financeDepartment"),
  financeDepartmentInterior: md5("financeDepartmentInterior"),
  financeDepartmentInteriorPart2: md5("financeDepartmentInteriorPart2"),
  financeStationaryCupboard: md5("financeStationaryCupboard"),
  valComputer: md5("valComputer"),
  financeStationaryCupboardInterior: md5("financeStationaryCupboardInterior"),
  valComputerInterior: md5("valComputerInterior"),
  financeDepartmentSeat: md5("financeDepartmentSeat"),
  financeDepartmentSafe: md5("financeDepartmentSafe"),
  financeDepartmentSafeInterior: md5("financeDepartmentSafeInterior"),
  exit: md5("exit"),
};

module.exports = pageKeys;
